// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

export namespace std {
  using std::isalnum VSTD_USING_IF_EXISTS;
  using std::isalpha VSTD_USING_IF_EXISTS;
  using std::isblank VSTD_USING_IF_EXISTS;
  using std::iscntrl VSTD_USING_IF_EXISTS;
  using std::isdigit VSTD_USING_IF_EXISTS;
  using std::isgraph VSTD_USING_IF_EXISTS;
  using std::islower VSTD_USING_IF_EXISTS;
  using std::isprint VSTD_USING_IF_EXISTS;
  using std::ispunct VSTD_USING_IF_EXISTS;
  using std::isspace VSTD_USING_IF_EXISTS;
  using std::isupper VSTD_USING_IF_EXISTS;
  using std::isxdigit VSTD_USING_IF_EXISTS;
  using std::tolower VSTD_USING_IF_EXISTS;
  using std::toupper VSTD_USING_IF_EXISTS;
} // namespace std
