// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

export namespace std {

  using std::double_t VSTD_USING_IF_EXISTS;
  using std::float_t VSTD_USING_IF_EXISTS;

  using std::acos VSTD_USING_IF_EXISTS;
  using std::acosf VSTD_USING_IF_EXISTS;
  using std::acosl VSTD_USING_IF_EXISTS;

  using std::asin VSTD_USING_IF_EXISTS;
  using std::asinf VSTD_USING_IF_EXISTS;
  using std::asinl VSTD_USING_IF_EXISTS;

  using std::atan VSTD_USING_IF_EXISTS;
  using std::atanf VSTD_USING_IF_EXISTS;
  using std::atanl VSTD_USING_IF_EXISTS;

  using std::atan2 VSTD_USING_IF_EXISTS;
  using std::atan2f VSTD_USING_IF_EXISTS;
  using std::atan2l VSTD_USING_IF_EXISTS;

  using std::cos VSTD_USING_IF_EXISTS;
  using std::cosf VSTD_USING_IF_EXISTS;
  using std::cosl VSTD_USING_IF_EXISTS;

  using std::sin VSTD_USING_IF_EXISTS;
  using std::sinf VSTD_USING_IF_EXISTS;
  using std::sinl VSTD_USING_IF_EXISTS;

  using std::tan VSTD_USING_IF_EXISTS;
  using std::tanf VSTD_USING_IF_EXISTS;
  using std::tanl VSTD_USING_IF_EXISTS;

  using std::acosh VSTD_USING_IF_EXISTS;
  using std::acoshf VSTD_USING_IF_EXISTS;
  using std::acoshl VSTD_USING_IF_EXISTS;

  using std::asinh VSTD_USING_IF_EXISTS;
  using std::asinhf VSTD_USING_IF_EXISTS;
  using std::asinhl VSTD_USING_IF_EXISTS;

  using std::atanh VSTD_USING_IF_EXISTS;
  using std::atanhf VSTD_USING_IF_EXISTS;
  using std::atanhl VSTD_USING_IF_EXISTS;

  using std::cosh VSTD_USING_IF_EXISTS;
  using std::coshf VSTD_USING_IF_EXISTS;
  using std::coshl VSTD_USING_IF_EXISTS;

  using std::sinh VSTD_USING_IF_EXISTS;
  using std::sinhf VSTD_USING_IF_EXISTS;
  using std::sinhl VSTD_USING_IF_EXISTS;

  using std::tanh VSTD_USING_IF_EXISTS;
  using std::tanhf VSTD_USING_IF_EXISTS;
  using std::tanhl VSTD_USING_IF_EXISTS;

  using std::exp VSTD_USING_IF_EXISTS;
  using std::expf VSTD_USING_IF_EXISTS;
  using std::expl VSTD_USING_IF_EXISTS;

  using std::exp2 VSTD_USING_IF_EXISTS;
  using std::exp2f VSTD_USING_IF_EXISTS;
  using std::exp2l VSTD_USING_IF_EXISTS;

  using std::expm1 VSTD_USING_IF_EXISTS;
  using std::expm1f VSTD_USING_IF_EXISTS;
  using std::expm1l VSTD_USING_IF_EXISTS;

  using std::frexp VSTD_USING_IF_EXISTS;
  using std::frexpf VSTD_USING_IF_EXISTS;
  using std::frexpl VSTD_USING_IF_EXISTS;

  using std::ilogb VSTD_USING_IF_EXISTS;
  using std::ilogbf VSTD_USING_IF_EXISTS;
  using std::ilogbl VSTD_USING_IF_EXISTS;

  using std::ldexp VSTD_USING_IF_EXISTS;
  using std::ldexpf VSTD_USING_IF_EXISTS;
  using std::ldexpl VSTD_USING_IF_EXISTS;

  using std::log VSTD_USING_IF_EXISTS;
  using std::logf VSTD_USING_IF_EXISTS;
  using std::logl VSTD_USING_IF_EXISTS;

  using std::log10 VSTD_USING_IF_EXISTS;
  using std::log10f VSTD_USING_IF_EXISTS;
  using std::log10l VSTD_USING_IF_EXISTS;

  using std::log1p VSTD_USING_IF_EXISTS;
  using std::log1pf VSTD_USING_IF_EXISTS;
  using std::log1pl VSTD_USING_IF_EXISTS;

  using std::log2 VSTD_USING_IF_EXISTS;
  using std::log2f VSTD_USING_IF_EXISTS;
  using std::log2l VSTD_USING_IF_EXISTS;

  using std::logb VSTD_USING_IF_EXISTS;
  using std::logbf VSTD_USING_IF_EXISTS;
  using std::logbl VSTD_USING_IF_EXISTS;

  using std::modf VSTD_USING_IF_EXISTS;
  using std::modff VSTD_USING_IF_EXISTS;
  using std::modfl VSTD_USING_IF_EXISTS;

  using std::scalbn VSTD_USING_IF_EXISTS;
  using std::scalbnf VSTD_USING_IF_EXISTS;
  using std::scalbnl VSTD_USING_IF_EXISTS;

  using std::scalbln VSTD_USING_IF_EXISTS;
  using std::scalblnf VSTD_USING_IF_EXISTS;
  using std::scalblnl VSTD_USING_IF_EXISTS;

  using std::cbrt VSTD_USING_IF_EXISTS;
  using std::cbrtf VSTD_USING_IF_EXISTS;
  using std::cbrtl VSTD_USING_IF_EXISTS;

  // [c.math.abs], absolute values
  using std::abs VSTD_USING_IF_EXISTS;

  using std::fabs VSTD_USING_IF_EXISTS;
  using std::fabsf VSTD_USING_IF_EXISTS;
  using std::fabsl VSTD_USING_IF_EXISTS;

  using std::hypot VSTD_USING_IF_EXISTS;
  using std::hypotf VSTD_USING_IF_EXISTS;
  using std::hypotl VSTD_USING_IF_EXISTS;

  // [c.math.hypot3], three-dimensional hypotenuse

  using std::pow VSTD_USING_IF_EXISTS;
  using std::powf VSTD_USING_IF_EXISTS;
  using std::powl VSTD_USING_IF_EXISTS;

  using std::sqrt VSTD_USING_IF_EXISTS;
  using std::sqrtf VSTD_USING_IF_EXISTS;
  using std::sqrtl VSTD_USING_IF_EXISTS;

  using std::erf VSTD_USING_IF_EXISTS;
  using std::erff VSTD_USING_IF_EXISTS;
  using std::erfl VSTD_USING_IF_EXISTS;

  using std::erfc VSTD_USING_IF_EXISTS;
  using std::erfcf VSTD_USING_IF_EXISTS;
  using std::erfcl VSTD_USING_IF_EXISTS;

  using std::lgamma VSTD_USING_IF_EXISTS;
  using std::lgammaf VSTD_USING_IF_EXISTS;
  using std::lgammal VSTD_USING_IF_EXISTS;

  using std::tgamma VSTD_USING_IF_EXISTS;
  using std::tgammaf VSTD_USING_IF_EXISTS;
  using std::tgammal VSTD_USING_IF_EXISTS;

  using std::ceil VSTD_USING_IF_EXISTS;
  using std::ceilf VSTD_USING_IF_EXISTS;
  using std::ceill VSTD_USING_IF_EXISTS;

  using std::floor VSTD_USING_IF_EXISTS;
  using std::floorf VSTD_USING_IF_EXISTS;
  using std::floorl VSTD_USING_IF_EXISTS;

  using std::nearbyint VSTD_USING_IF_EXISTS;
  using std::nearbyintf VSTD_USING_IF_EXISTS;
  using std::nearbyintl VSTD_USING_IF_EXISTS;

  using std::rint VSTD_USING_IF_EXISTS;
  using std::rintf VSTD_USING_IF_EXISTS;
  using std::rintl VSTD_USING_IF_EXISTS;

  using std::lrint VSTD_USING_IF_EXISTS;
  using std::lrintf VSTD_USING_IF_EXISTS;
  using std::lrintl VSTD_USING_IF_EXISTS;

  using std::llrint VSTD_USING_IF_EXISTS;
  using std::llrintf VSTD_USING_IF_EXISTS;
  using std::llrintl VSTD_USING_IF_EXISTS;

  using std::round VSTD_USING_IF_EXISTS;
  using std::roundf VSTD_USING_IF_EXISTS;
  using std::roundl VSTD_USING_IF_EXISTS;

  using std::lround VSTD_USING_IF_EXISTS;
  using std::lroundf VSTD_USING_IF_EXISTS;
  using std::lroundl VSTD_USING_IF_EXISTS;

  using std::llround VSTD_USING_IF_EXISTS;
  using std::llroundf VSTD_USING_IF_EXISTS;
  using std::llroundl VSTD_USING_IF_EXISTS;

  using std::trunc VSTD_USING_IF_EXISTS;
  using std::truncf VSTD_USING_IF_EXISTS;
  using std::truncl VSTD_USING_IF_EXISTS;

  using std::fmod VSTD_USING_IF_EXISTS;
  using std::fmodf VSTD_USING_IF_EXISTS;
  using std::fmodl VSTD_USING_IF_EXISTS;

  using std::remainder VSTD_USING_IF_EXISTS;
  using std::remainderf VSTD_USING_IF_EXISTS;
  using std::remainderl VSTD_USING_IF_EXISTS;

  using std::remquo VSTD_USING_IF_EXISTS;
  using std::remquof VSTD_USING_IF_EXISTS;
  using std::remquol VSTD_USING_IF_EXISTS;

  using std::copysign VSTD_USING_IF_EXISTS;
  using std::copysignf VSTD_USING_IF_EXISTS;
  using std::copysignl VSTD_USING_IF_EXISTS;

  using std::nan VSTD_USING_IF_EXISTS;
  using std::nanf VSTD_USING_IF_EXISTS;
  using std::nanl VSTD_USING_IF_EXISTS;

  using std::nextafter VSTD_USING_IF_EXISTS;
  using std::nextafterf VSTD_USING_IF_EXISTS;
  using std::nextafterl VSTD_USING_IF_EXISTS;

  using std::nexttoward VSTD_USING_IF_EXISTS;
  using std::nexttowardf VSTD_USING_IF_EXISTS;
  using std::nexttowardl VSTD_USING_IF_EXISTS;

  using std::fdim VSTD_USING_IF_EXISTS;
  using std::fdimf VSTD_USING_IF_EXISTS;
  using std::fdiml VSTD_USING_IF_EXISTS;

  using std::fmax VSTD_USING_IF_EXISTS;
  using std::fmaxf VSTD_USING_IF_EXISTS;
  using std::fmaxl VSTD_USING_IF_EXISTS;

  using std::fmin VSTD_USING_IF_EXISTS;
  using std::fminf VSTD_USING_IF_EXISTS;
  using std::fminl VSTD_USING_IF_EXISTS;

  using std::fma VSTD_USING_IF_EXISTS;
  using std::fmaf VSTD_USING_IF_EXISTS;
  using std::fmal VSTD_USING_IF_EXISTS;

  // [c.math.lerp], linear interpolation
  using std::lerp VSTD_USING_IF_EXISTS;

  // [c.math.fpclass], classification / comparison functions
  using std::fpclassify VSTD_USING_IF_EXISTS;
  using std::isfinite VSTD_USING_IF_EXISTS;
  using std::isgreater VSTD_USING_IF_EXISTS;
  using std::isgreaterequal VSTD_USING_IF_EXISTS;
  using std::isinf VSTD_USING_IF_EXISTS;
  using std::isless VSTD_USING_IF_EXISTS;
  using std::islessequal VSTD_USING_IF_EXISTS;
  using std::islessgreater VSTD_USING_IF_EXISTS;
  using std::isnan VSTD_USING_IF_EXISTS;
  using std::isnormal VSTD_USING_IF_EXISTS;
  using std::isunordered VSTD_USING_IF_EXISTS;
  using std::signbit VSTD_USING_IF_EXISTS;

  // [sf.cmath], mathematical special functions
#if 0
  // [sf.cmath.assoc.laguerre], associated Laguerre polynomials
  using std::assoc_laguerre;
  using std::assoc_laguerref;
  using std::assoc_laguerrel;

  // [sf.cmath.assoc.legendre], associated Legendre functions
  using std::assoc_legendre;
  using std::assoc_legendref;
  using std::assoc_legendrel;

  // [sf.cmath.beta], beta function
  using std::beta;
  using std::betaf;
  using std::betal;

  // [sf.cmath.comp.ellint.1], complete elliptic integral of the first kind
  using std::comp_ellint_1;
  using std::comp_ellint_1f;
  using std::comp_ellint_1l;

  // [sf.cmath.comp.ellint.2], complete elliptic integral of the second kind
  using std::comp_ellint_2;
  using std::comp_ellint_2f;
  using std::comp_ellint_2l;

  // [sf.cmath.comp.ellint.3], complete elliptic integral of the third kind
  using std::comp_ellint_3;
  using std::comp_ellint_3f;
  using std::comp_ellint_3l;

  // [sf.cmath.cyl.bessel.i], regular modified cylindrical Bessel functions
  using std::cyl_bessel_i;
  using std::cyl_bessel_if;
  using std::cyl_bessel_il;

  // [sf.cmath.cyl.bessel.j], cylindrical Bessel functions of the first kind
  using std::cyl_bessel_j;
  using std::cyl_bessel_jf;
  using std::cyl_bessel_jl;

  // [sf.cmath.cyl.bessel.k], irregular modified cylindrical Bessel functions
  using std::cyl_bessel_k;
  using std::cyl_bessel_kf;
  using std::cyl_bessel_kl;

  // [sf.cmath.cyl.neumann], cylindrical Neumann functions
  // cylindrical Bessel functions of the second kind
  using std::cyl_neumann;
  using std::cyl_neumannf;
  using std::cyl_neumannl;

  // [sf.cmath.ellint.1], incomplete elliptic integral of the first kind
  using std::ellint_1;
  using std::ellint_1f;
  using std::ellint_1l;

  // [sf.cmath.ellint.2], incomplete elliptic integral of the second kind
  using std::ellint_2;
  using std::ellint_2f;
  using std::ellint_2l;

  // [sf.cmath.ellint.3], incomplete elliptic integral of the third kind
  using std::ellint_3;
  using std::ellint_3f;
  using std::ellint_3l;

  // [sf.cmath.expint], exponential integral
  using std::expint;
  using std::expintf;
  using std::expintl;
#endif

  // [sf.cmath.hermite], Hermite polynomials
  using std::hermite;
  using std::hermitef;
  using std::hermitel;

#if 0
  // [sf.cmath.laguerre], Laguerre polynomials
  using std::laguerre;
  using std::laguerref;
  using std::laguerrel;

  // [sf.cmath.legendre], Legendre polynomials
  using std::legendre;
  using std::legendref;
  using std::legendrel;

  // [sf.cmath.riemann.zeta], Riemann zeta function
  using std::riemann_zeta;
  using std::riemann_zetaf;
  using std::riemann_zetal;

  // [sf.cmath.sph.bessel], spherical Bessel functions of the first kind
  using std::sph_bessel;
  using std::sph_besself;
  using std::sph_bessell;

  // [sf.cmath.sph.legendre], spherical associated Legendre functions
  using std::sph_legendre;
  using std::sph_legendref;
  using std::sph_legendrel;

  // [sf.cmath.sph.neumann], spherical Neumann functions;
  // spherical Bessel functions of the second kind
  using std::sph_neumann;
  using std::sph_neumannf;
  using std::sph_neumannl;
#endif
} // namespace std
