// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

export namespace std {
  using std::FILE VSTD_USING_IF_EXISTS;
  using std::fpos_t VSTD_USING_IF_EXISTS;
  using std::size_t VSTD_USING_IF_EXISTS;

  using std::clearerr VSTD_USING_IF_EXISTS;
  using std::fclose VSTD_USING_IF_EXISTS;
  using std::feof VSTD_USING_IF_EXISTS;
  using std::ferror VSTD_USING_IF_EXISTS;
  using std::fflush VSTD_USING_IF_EXISTS;
  using std::fgetc VSTD_USING_IF_EXISTS;
  using std::fgetpos VSTD_USING_IF_EXISTS;
  using std::fgets VSTD_USING_IF_EXISTS;
  using std::fopen VSTD_USING_IF_EXISTS;
  using std::fprintf VSTD_USING_IF_EXISTS;
  using std::fputc VSTD_USING_IF_EXISTS;
  using std::fputs VSTD_USING_IF_EXISTS;
  using std::fread VSTD_USING_IF_EXISTS;
  using std::freopen VSTD_USING_IF_EXISTS;
  using std::fscanf VSTD_USING_IF_EXISTS;
  using std::fseek VSTD_USING_IF_EXISTS;
  using std::fsetpos VSTD_USING_IF_EXISTS;
  using std::ftell VSTD_USING_IF_EXISTS;
  using std::fwrite VSTD_USING_IF_EXISTS;
  using std::getc VSTD_USING_IF_EXISTS;
  using std::getchar VSTD_USING_IF_EXISTS;
  using std::perror VSTD_USING_IF_EXISTS;
  using std::printf VSTD_USING_IF_EXISTS;
  using std::putc VSTD_USING_IF_EXISTS;
  using std::putchar VSTD_USING_IF_EXISTS;
  using std::puts VSTD_USING_IF_EXISTS;
  using std::remove VSTD_USING_IF_EXISTS;
  using std::rename VSTD_USING_IF_EXISTS;
  using std::rewind VSTD_USING_IF_EXISTS;
  using std::scanf VSTD_USING_IF_EXISTS;
  using std::setbuf VSTD_USING_IF_EXISTS;
  using std::setvbuf VSTD_USING_IF_EXISTS;
  using std::snprintf VSTD_USING_IF_EXISTS;
  using std::sprintf VSTD_USING_IF_EXISTS;
  using std::sscanf VSTD_USING_IF_EXISTS;
  using std::tmpfile VSTD_USING_IF_EXISTS;
  using std::tmpnam VSTD_USING_IF_EXISTS;
  using std::ungetc VSTD_USING_IF_EXISTS;
  using std::vfprintf VSTD_USING_IF_EXISTS;
  using std::vfscanf VSTD_USING_IF_EXISTS;
  using std::vprintf VSTD_USING_IF_EXISTS;
  using std::vscanf VSTD_USING_IF_EXISTS;
  using std::vsnprintf VSTD_USING_IF_EXISTS;
  using std::vsprintf VSTD_USING_IF_EXISTS;
  using std::vsscanf VSTD_USING_IF_EXISTS;
} // namespace std
