// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

export namespace std {
  using std::size_t VSTD_USING_IF_EXISTS;

  using std::memchr VSTD_USING_IF_EXISTS;
  using std::memcmp VSTD_USING_IF_EXISTS;
  using std::memcpy VSTD_USING_IF_EXISTS;
  using std::memmove VSTD_USING_IF_EXISTS;
  using std::memset VSTD_USING_IF_EXISTS;
  using std::strcat VSTD_USING_IF_EXISTS;
  using std::strchr VSTD_USING_IF_EXISTS;
  using std::strcmp VSTD_USING_IF_EXISTS;
  using std::strcoll VSTD_USING_IF_EXISTS;
  using std::strcpy VSTD_USING_IF_EXISTS;
  using std::strcspn VSTD_USING_IF_EXISTS;
  using std::strerror VSTD_USING_IF_EXISTS;
  using std::strlen VSTD_USING_IF_EXISTS;
  using std::strncat VSTD_USING_IF_EXISTS;
  using std::strncmp VSTD_USING_IF_EXISTS;
  using std::strncpy VSTD_USING_IF_EXISTS;
  using std::strpbrk VSTD_USING_IF_EXISTS;
  using std::strrchr VSTD_USING_IF_EXISTS;
  using std::strspn VSTD_USING_IF_EXISTS;
  using std::strstr VSTD_USING_IF_EXISTS;
  using std::strtok VSTD_USING_IF_EXISTS;
  using std::strxfrm VSTD_USING_IF_EXISTS;
} // namespace std
