include("${INPUT}")
foreach(required compiler glfw_file glfw_header slang_compiler)
    if(NOT EXISTS "${${required}}")
        message(FATAL_ERROR "Backend identity input is missing ${required}: ${${required}}")
    endif()
endforeach()
function(source_fingerprint output)
    set(files ${ARGN})
    list(SORT files)
    set(material "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" digest)
        file(RELATIVE_PATH relative "${source_root}" "${path}")
        string(APPEND material "${relative}=${digest}\n")
    endforeach()
    string(SHA256 result "${material}")
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
source_fingerprint(contract_source_id ${contract_files})
source_fingerprint(shader_source_id ${shader_files})
source_fingerprint(backend_source_id ${backend_files})
set(stdlib_material "")
list(SORT stdlib_files)
foreach(path IN LISTS stdlib_files)
    file(SHA256 "${path}" digest)
    get_filename_component(name "${path}" NAME)
    string(APPEND stdlib_material "${name}=${digest}\n")
endforeach()
string(SHA256 stdlib_build_id "${stdlib_material}")
file(SHA256 "${compiler}" compiler_sha256)
file(SHA256 "${glfw_file}" glfw_sha256)
file(SHA256 "${glfw_header}" glfw_header_sha256)
file(SHA256 "${slang_compiler}" slang_sha256)
file(READ "${source_root}/promise/rhi/rhi.contract.cppm" abi_source)
string(REGEX MATCH "abi_version[ \t\r\n]*=[ \t\r\n]*([0-9]+)u" abi_match "${abi_source}")
if(NOT abi_match)
    message(FATAL_ERROR "Cannot extract the actual contract ABI")
endif()
set(contract_abi "${CMAKE_MATCH_1}")
file(READ "${glfw_header}" glfw_source)
set(glfw_version "")
foreach(part MAJOR MINOR REVISION)
    string(REGEX MATCH "#define[ \t]+GLFW_VERSION_${part}[ \t]+([0-9]+)" found "${glfw_source}")
    if(NOT found)
        message(FATAL_ERROR "Cannot extract GLFW ${part} from the configured header")
    endif()
    if(glfw_version)
        string(APPEND glfw_version ".")
    endif()
    string(APPEND glfw_version "${CMAKE_MATCH_1}")
endforeach()
# stdlib/CRT identity includes installed runtime/header hashes plus the actual driver/link configuration.
# The final runtime DLL import set is separately recorded in the staged PE dependency inventory.
set(toolchain "")
foreach(field compiler_id compiler_version compiler_target compiler_sha256 architecture configuration
              cxx_standard global_cxx_flags config_cxx_flags host_options backend_options loader_options
              host_definitions backend_definitions msvc_runtime implicit_link_libraries
              stdlib_build_id)
    string(APPEND toolchain "${field}=${${field}}\n")
endforeach()
string(SHA256 compat_id "abi=${contract_abi}\ncontract=${contract_source_id}\n${toolchain}glfw=${glfw_version}:${glfw_sha256}:${glfw_header_sha256}\n")
string(SHA256 shader_interface_id "source=${shader_source_id}\nslang=${slang_sha256}\nentries=${shader_entries}\noptions=${shader_compile_contract}\n")
string(SHA256 build_digest "backend=${backend_source_id}\ncompat=${compat_id}\nshaders=${shader_interface_id}\n")
string(SUBSTRING "${build_digest}" 0 24 build_short)
set(backend_build_id "vulkan-${build_short}")
set(header "#pragma once\nnamespace deren::backend_identity {\ninline constexpr unsigned contract_abi = ${contract_abi}u;\n")
foreach(field compat_id shader_interface_id glfw_version glfw_sha256)
    string(APPEND header "inline constexpr char ${field}[] = \"${${field}}\";\n")
endforeach()
string(APPEND header "}\n")
set(manifest "{}")
string(JSON manifest SET "${manifest}" manifest_schema 1)
string(JSON manifest SET "${manifest}" contract_abi "${contract_abi}")
foreach(field compat_id shader_interface_id backend_build_id glfw_version glfw_sha256 compiler_id
              compiler_version compiler_target compiler_sha256 contract_source_id shader_source_id
              configuration architecture cxx_standard msvc_runtime stdlib_build_id shader_compile_contract)
    set(value "${${field}}")
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    string(JSON manifest SET "${manifest}" "${field}" "\"${value}\"")
endforeach()
string(JSON manifest SET "${manifest}" minimum_system "\"Windows 10 x64\"")
if(host_options MATCHES "march=native")
    set(cpu "build-machine native CPU feature set; not a portable release")
elseif(host_options MATCHES "march=x86-64-v3")
    set(cpu "x86-64-v3")
else()
    set(cpu "x86-64 (exact architecture options are included in compat_id)")
endif()
string(JSON manifest SET "${manifest}" minimum_cpu "\"${cpu}\"")
string(JSON manifest SET "${manifest}" gpu_requirements "\"Vulkan 1.3 dynamicRendering; VK_KHR_swapchain; VK_EXT_descriptor_heap and VK_KHR_maintenance5 or VK_KHR_extended_flags; VK_KHR_shader_untyped_pointers.shaderUntypedPointers; VK_KHR_unified_image_layouts.unifiedImageLayouts; VK_EXT_host_image_copy.hostImageCopy with GENERAL source and destination layouts. Feature-specific optional requirements remain in backend startup diagnostics.\"")
file(MAKE_DIRECTORY "${output_directory}")
function(write_if_changed path content)
    if(EXISTS "${path}")
        file(READ "${path}" old)
        if(old STREQUAL content)
            return()
        endif()
    endif()
    file(WRITE "${path}" "${content}")
endfunction()
write_if_changed("${output_directory}/deren_backend_identity.hpp" "${header}")
write_if_changed("${output_directory}/backend.manifest.seed.json" "${manifest}\n")
