file(READ "${SEED}" manifest)
string(JSON build_id GET "${manifest}" backend_build_id)
if(NOT build_id MATCHES "^vulkan-[0-9a-f]+$")
    message(FATAL_ERROR "Unsafe backend build ID")
endif()
get_filename_component(host_dir "${HOST}" DIRECTORY)
set(backend_dir "${host_dir}/backends/vulkan/${build_id}")
file(MAKE_DIRECTORY "${backend_dir}")
file(SHA256 "${BACKEND}" backend_sha256)
file(SHA256 "${GLFW}" glfw_sha256)
string(JSON expected_glfw GET "${manifest}" glfw_sha256)
if(NOT glfw_sha256 STREQUAL expected_glfw)
    message(FATAL_ERROR "GLFW changed after release identity generation; rebuild the package")
endif()
file(COPY_FILE "${BACKEND}" "${backend_dir}/deren_vulkan.dll" ONLY_IF_DIFFERENT)
file(COPY_FILE "${GLFW}" "${host_dir}/glfw3.dll" ONLY_IF_DIFFERENT)
string(JSON manifest SET "${manifest}" backend_sha256 "\"${backend_sha256}\"")
file(WRITE "${backend_dir}/backend.manifest.json" "${manifest}\n")
if(NOT IS_DIRECTORY "${SHADERS}")
    message(FATAL_ERROR "Compiled shader directory is missing: ${SHADERS}")
endif()
if(NOT SHADERS STREQUAL "${host_dir}/shaders")
    file(COPY "${SHADERS}" DESTINATION "${host_dir}")
endif()
message(STATUS "Staged first-party backend ${build_id}: ${backend_sha256}")
